'use client';

export type ExportColumn<T> = {
  key: string;
  label: string;
  format?: (row: T) => string | number;
};

export function exportToCSV<T>(
  filename: string,
  columns: ExportColumn<T>[],
  rows: T[],
  options?: { summaryRows?: { label: string; values: Record<string, string | number> }[] },
) {
  if (rows.length === 0) return;
  const headers = columns.map((c) => c.label);
  const dataLines = rows.map((row) =>
    columns
      .map((c) => {
        const val = c.format ? c.format(row) : (row as any)[c.key];
        const str = val == null ? '' : String(val);
        return `"${str.replace(/"/g, '""')}"`;
      })
      .join(','),
  );
  const allLines = [headers.map((h) => `"${h}"`).join(','), ...dataLines];

  if (options?.summaryRows) {
    for (const s of options.summaryRows) {
      const line = columns.map((c) => {
        const val = s.values[c.key] ?? '';
        return `"${String(val).replace(/"/g, '""')}"`;
      });
      allLines.push(line.join(','));
    }
  }

  const csv = '\uFEFF' + allLines.join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToHTML<T>(
  title: string,
  subtitle: string,
  columns: ExportColumn<T>[],
  rows: T[],
  options?: {
    summaryRows?: { label: string; values: Record<string, string | number> }[];
    filterSummary?: string;
  },
): string {
  const headerCells = columns.map((c) => `<th>${escapeHtml(c.label)}</th>`).join('');
  const bodyRows = rows
    .map(
      (row) =>
        `<tr>${columns
          .map((c) => {
            const val = c.format ? c.format(row) : (row as any)[c.key];
            return `<td>${escapeHtml(val == null ? '' : String(val))}</td>`;
          })
          .join('')}</tr>`,
    )
    .join('');

  const summaryRows = options?.summaryRows
    ? options.summaryRows
        .map(
          (s) =>
            `<tr class="summary-row">${columns
              .map((c) => `<td>${escapeHtml(String(s.values[c.key] ?? ''))}</td>`)
              .join('')}</tr>`,
        )
        .join('')
    : '';

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 20px; color: #1a1a2e; }
  .report-header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
  .report-header h1 { margin: 0; font-size: 22px; color: #2563eb; }
  .report-header h2 { margin: 4px 0; font-size: 16px; }
  .report-header p { margin: 2px 0; font-size: 12px; color: #666; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th { background: #2563eb; color: #fff; padding: 6px 8px; text-align: left; font-weight: 600; }
  td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) { background: #f9fafb; }
  .summary-row { font-weight: bold; background: #eff6ff !important; border-top: 2px solid #2563eb; }
  .footer { margin-top: 20px; text-align: center; font-size: 10px; color: #999; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>
  <div class="report-header">
    <h1>LABSTACK</h1>
    <h2>${escapeHtml(title)}</h2>
    <p>${escapeHtml(subtitle)}</p>
    ${options?.filterSummary ? `<p>${escapeHtml(options.filterSummary)}</p>` : ''}
    <p>Generated: ${new Date().toLocaleString()}</p>
  </div>
  <table>
    <thead><tr>${headerCells}</tr></thead>
    <tbody>${bodyRows}${summaryRows}</tbody>
  </table>
  <div class="footer">Generated by LabStack ERP &middot; ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

export function printHTML(html: string) {
  const w = window.open('', '_blank', 'width=1000,height=700');
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}

export function exportAndPrint<T>(
  title: string,
  subtitle: string,
  columns: ExportColumn<T>[],
  rows: T[],
  options?: {
    summaryRows?: { label: string; values: Record<string, string | number> }[];
    filterSummary?: string;
  },
) {
  const html = exportToHTML(title, subtitle, columns, rows, options);
  printHTML(html);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function formatCurrency(n: number | string | null | undefined): string {
  const v = Number(n) || 0;
  return v.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
}

export function formatDate(d: string | null | undefined): string {
  if (!d) return '-';
  try {
    return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  } catch {
    return '-';
  }
}

export function formatDateTime(d: string | null | undefined): string {
  if (!d) return '-';
  try {
    return new Date(d).toLocaleString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return '-';
  }
}
